berlyne/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url('^', include('wui.urls')),
    url(r'^vm/', include('vmmanage.urls'))
]

wui/urls.py
# Berlyne IT security trainings platform
# Copyright (C) 2016 Ruben Gonzalez <rg@ht11.org>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
from django.conf.urls import url, include
from . import views

urlpatterns = [
    url(r'^$', views.index, name='wui_index'),
    url(r'^pages', include('django.contrib.flatpages.urls')),
    url(r'^accounts/', include(
        [
            url(r'^profile/$', views.profile, name='wui_acc_profile'),
            url(r'^register/$', views.register, name='wui_acc_register'),
            url(r'^', include('django.contrib.auth.urls')),
        ]
    )),
    url(r'^course_create/$', views.course_edit, name='wui_course_create'),
    url(r'^course/$', views.courses, name='wui_courses'),
    url(r'^course/(?P<course_slug>[\w-]+)/', include(
        [
            url(r'^edit/$', views.course_edit, name='wui_course_edit'),
            url(r'^$', views.course_show, name='wui_course_show'),
            url(r'^delete/$', views.course_delete, name='wui_course_delete'),
            url(r'^join/$', views.course_join, name='wui_course_join'),
            url(r'^join_pw/$', views.course_join_pw, name='wui_course_join_pw'),
            url(r'^leave/$', views.course_leave, name='wui_course_leave'),
            url(r'^problems/$', views.course_problems, name='wui_course_problems'),
            url(r'^problem_writeup/(?P<problem_slug>[\w.,-]+)/$', views.writeup, name='wui_course_problem_writeup'),
            url(r'^scoreboard/$', views.course_scoreboard, name='wui_course_scoreboard'),
            url(r'^manage_problems/$', views.course_manage_problems, name='wui_course_manage_problems'),
            url(r'^manage_points/$', views.course_manage_points, name='wui_points_to_problems'),
            url(r'^writeups/$', views.course_writeups, name='wui_course_writeups'),
            url(r'^writeups/(?P<problem_name>[\w.,-]+)/(?P<user_name>[\w.,-]+)/$', views.show_writeup, name='wui_course_writeup_show')
        ]
    )),
    url(r'^downloads/(?P<download_id>[\w-]+)/$', views.download_file, name='wui_download_file'),
]

vmapi/models.py
from django.db import models

from autotask import models as task_models
from .uptomate import Deployment

DEFAULT_TASK_NAME = "unnamed_task"
TASK_STATUS_NAMES = dict(task_models.STATUS_CHOICES)


class VirtualMachine(models.Model):
    slug = models.SlugField(unique=True)
    created_at = models.DateTimeField(auto_now_add=True)
    ip_addr = models.CharField(max_length=45)

    # Attrs used from config
    desc = models.TextField(max_length=1024)
    category = models.CharField(max_length=255)
    flag = models.CharField(max_length=255)

    # Stores config of problem running on this machine
    __vagr_config = None

    def __get_problem_config(self):
        if not self.__vagr_config:
            vagr = Deployment.Vagrant(self.slug)
            self.__vagr_config = vagr.get_config()
        return self.__vagr_config.copy()

    def get_problem_config(self):
        return self.__get_problem_config()

    def add_task(self, async_result):
        self.task_set.add(Task.create(self, async_result), bulk=False)

    def __str__(self):
        return self.slug


class Port(models.Model):
    number = models.IntegerField(primary_key=True)
    vm = models.ForeignKey(VirtualMachine, on_delete=models.CASCADE)


class Task(models.Model):
    """
    Used to link a task to a virtual machine.
    This should always be created using the factory methods
    given.
    """
    virtual_machine = models.ForeignKey(VirtualMachine, on_delete=models.CASCADE)
    task = models.ForeignKey(task_models.TaskQueue)
    creation_date = models.DateTimeField(auto_now_add=True)

    # Factory method
    @classmethod
    def create(cls, virtual_machine, task):
        return cls(virtual_machine=virtual_machine,
                   task_id=task.pk)

    @classmethod
    def create_and_launch(cls, virtual_machine, task, **task_kwargs):
        """
        Creates an entry and launches the task
        :param virtual_machine: vm to link to
        :param task: task to run
        :param task_kwargs: task arguments
        :return: Task instance
        """
        return Task.create(virtual_machine, task(**task_kwargs))

    def to_dict(self, json_parsable=True):
        task_dict = {
            'task_name': self.task.function,
            'task_id': self.task.pk,
            'state': TASK_STATUS_NAMES[self.task.status]
        }

        res = None
        if self.task.status == task_models.DONE:
            res = self.task.result
        if self.task.status == task_models.ERROR:
            res = self.task.error_message
        if res is not None:
            task_dict['result'] = str(res) if json_parsable else res

        vm = self.virtual_machine
        task_dict['vm'] = str(vm) if json_parsable else vm

        return task_dict

    def __str__(self):
        return "<Task: {}>".format(self.task_id)

wui/models.py
# Berlyne IT security trainings platform
# Copyright (C) 2016 Ruben Gonzalez <rg@ht11.org>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
from django.contrib.auth import models as auth_models
from django.db import models
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _

import vmmanage.models


class Course(models.Model):
    name = models.SlugField(_('name'), unique=True)
    description = models.TextField(_('description'), max_length=1024)
    creation_time = models.DateTimeField(_('creation date'), auto_now_add=True)
    show_scoreboard = models.BooleanField(_('show scoreboard'), default=True)

    teacher = models.ForeignKey(auth_models.User,
                                related_name='teacher_courses', on_delete=models.CASCADE)
    participants = models.ManyToManyField(auth_models.User)

    # Pre shared key needed to join
    password = models.CharField(_('password'), max_length=255, blank=True, default="")

    # Points needed to pass
    point_threshold = models.IntegerField(_('point threshold'), )

    # Date time until when submission is open
    start_time = models.DateTimeField(_("start time"))
    deadline = models.DateTimeField(_("submission deadline"))

    # instances of problems (VMs)
    problems = models.ManyToManyField(vmmanage.models.Problem,
                                      through='CourseProblems')

    writeups = models.BooleanField(_("activate write ups"))

    @property
    def has_ended(self):
        return self.deadline < timezone.now()

    @property
    def has_begun(self):
        return self.start_time < timezone.now()

    def __str__(self):
        return "{} ({})".format(
            self.name,
            self.teacher.last_name or self.teacher.username
        )

    def has_user(self, user):
        if not isinstance(user, str):
            user = user.username

        return self.participants.filter(username=user).exists()


class CourseProblems(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    problem = models.ForeignKey(
        vmmanage.models.Problem,
        on_delete=models.CASCADE
    )
    points = models.IntegerField()

    class Meta:
        unique_together = ('course', 'problem')

    @staticmethod
    def check_problem_flag(course, problem_slug, flag):
        cp = CourseProblems.objects.get(
            course=course,
            problem__slug=problem_slug
        )
        correct = cp.problem.flag == flag
        return correct, cp

    def __str__(self):
        return "{}[{}]".format(str(self.problem).capitalize(), self.points)


class Submission(models.Model):
    flag = models.CharField(_('flag'), max_length=255)
    problem = models.ForeignKey(CourseProblems, on_delete=models.CASCADE)
    creation_time = models.DateTimeField(auto_now_add=True)
    correct = models.BooleanField(_('correct'))
    writeup = models.TextField(_('write up'), null=True)
    user = models.ForeignKey(auth_models.User, on_delete=models.CASCADE)

    class Meta:
        unique_together = ('flag', 'correct', 'user', 'problem')

    def __str__(self):
        return "<{}:{}>".format(self.correct, self.flag)

templates/vms/destroy_submission.html
{% extends "base.html" %}
{% load vm_extra %}
{% load i18n %}
{% block title %}{{ problem.slug }} - {{ problem.name }}{% endblock %}
{% block content %}
    <h1>{{ problem.slug }} - {{ problem.name }}</h1>
    <hr>
    <div>
        <div class="row">
            <h3>{% trans "Do you really want to destroy this problem?" %}</h3>
            <form method="POST">
                {% csrf_token %}
                <input type="submit" value="{% trans 'Destroy' %}" class="btn btn-danger">
            </form>
        </div>
        <div class="row">
            {% trans "(Destroying might take a while)" %}
        </div>

        <div class="row" style="margin-top: 20px">
            {% if problem.course_set.exists %}
                {% trans "<strong>This will delete all data connected to the problem, including writeups etc.</strong>" %}
                <br />
                {% trans "Problem is associated with the course(s):" %}
                <ul style="list-style-type: none">
                    {% for c in problem.course_set.all %}
                        <li>{{ c.name }}</li>
                    {% endfor %}
                </ul>
            {% else %}
                <h3>{% trans "Problem is not associated with any course" %}</h3>
            {% endif %}
        </div>
    </div>
{% endblock %}

templates/vms/detail.html
{% extends "base.html" %}
{% load vm_extra %}
{% load i18n %}
{% block title %}{{ problem.slug }} - {{ problem.name }}{% endblock %}
{% block content %}
    <h1>{{ problem.slug }} - {% trans 'details' %}</h1>
    <div class="row">
        <div class="panel panel-default">
              <!-- Default panel contents -->
              <div class="panel-heading">{{ problem.slug }} - {{ problem.name }}
                  <a href="{% url 'vmmanage_edit_problem' problem.slug %}"  class="btn btn-info">Edit</a>
              </div>
              <div class="panel-body">
              <ul class="list-group">
                <li class="list-group-item"><strong>{% trans 'Created' %}</strong>: {{ problem.created_at }}</li>
                <li class="list-group-item"><strong>{% trans 'Description' %}</strong>:<br /> {{ problem.desc }}</li>
                {% if problem.vm %}
                <li class="list-group-item"><strong>{% trans 'IP-Address' %}</strong>: {{ problem.vm.ip_addr }}</li>
                <li class="list-group-item"><strong>{% trans 'Provider' %}</strong>: {{ problem.vm.provider }}</li>
                <li class="list-group-item"><strong>{% trans 'Ports' %}</strong>:
                    {% for port in problem.vm.port_set.all %}{{ port }}{% endfor %}
                {% endif %}
                <li class="list-group-item"><strong>{% trans 'Category' %}</strong>: {{ problem.category }}</li>
                <li class="list-group-item"><strong>{% trans 'Tags' %}</strong>: {{ problem.tag_set.all|joinby:", "}}</li>
                <li class="list-group-item"><strong>{% trans 'Downloads' %}</strong>:<br />
                    {% for dl in problem.download_set.all %}{{ dl }}<br />{% endfor %}
                </li>

                <li class="list-group-item"><strong>{% trans 'Flag' %}</strong>: {{ problem.flag }}</li>
              </ul>

                <p>{% trans 'Manually perform tasks on the problem:' %}</p>
                  <div>
                      {% if problem.vm %}
                          {% for action in actions %}
                              <span>
                                 <a href="{% url 'vmmanage_perform_action' problem.slug action %}" class="btn btn-primary">{{ action|capfirst }}</a>
                              </span>
                          {% endfor %}
                      {% endif %}
                      <a href="{% url 'vmmanage_problem_destroy' problem.slug %}" class="btn btn-danger">{% trans "Destroy" %}</a>
                  </div>
              </div>
            </div>
    </div>

    {% if problem.vm %}
    <div class="row">
        <div class="col-md-6">
            <div class="panel panel-default">
              <!-- Default panel contents -->
              <div class="panel-heading">{% trans 'States' %}</div>
              <div class="panel-body">
                <table class="table">
                    <thead>
                      <tr>
                        <th>{% trans 'Name' %}</th>
                        <th>{% trans 'Time checked' %}</th>
                      </tr>
                    </thead>
                    <tbody>
                    {% for state in problem.vm.state_set.all %}
                              <tr>
                                <td>{{ state.name }}</td>
                                <td>{{ state.created }}</td>
                              </tr>
                    {% endfor %}
                </table>
              </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="panel panel-default">

              <div class="panel-heading">{% trans 'Tasks' %}</div>
              <div class="panel-body">
                <table class="table">
                    <thead>
                      <tr>
                        <th>{% trans 'Name' %}</th>
                        <th>{% trans 'Created' %}</th>
                        <th>{% trans 'State' %}</th>
                      </tr>
                    </thead>
                    <tbody>
                    {% for task in problem.vm.task_set.all %}
                          <tr data-toggle="collapse" data-target="#accordion-{{ task.task.pk }}" class="clickable {{ task.task.status|task_css_class }}">
                            <td>{{ task.task_name }}</td>
                            <td>{{ task.creation_date }}</td>
                            <td>{{ task.get_state_name }}</td>
                          </tr>
                          <tr>
                            <td colspan="3">
                                <div id="accordion-{{ task.task.pk }}" class="collapse">
                                    <strong>{% trans "Result" %}</strong>: {{ task.task.result.value_to_string }}
                                    <br />
                                    <strong>{% trans "Error" %}</strong>: {{ task.task.error_message }}
                                </div>
                            </td>
                          </tr>
                    {% endfor %}
                    </tbody>
                </table>
              </div>


            </div>
        </div>
    </div>
    {% endif %}
{% endblock %}

templates/vms/edit.html
{% extends "base.html" %}
{% load vm_extra %}
{% load i18n %}
{% block title %}{% trans "Edit" %} {{ problem.slug }} {% endblock %}
{% block content %}

{% if form.errors %}
            <div class="alert alert-danger">
                <p>{% blocktrans count form.errors.items|length as counter %}Please correct the error below.{% plural %}Please correct the errors below.{% endblocktrans %}</p>
            </div>
{% endif %}

<form method="POST">
    {% csrf_token %}

    {% for field in form %}
        {% include 'registration/form_field.html' %}
    {% endfor %}

    <input type="submit" value="{% trans "Save" %}" class="btn btn-default" />
    <a href="{% url "vmmanage_detail_problem" problem.slug %}" class="btn btn-danger" />Back</a>
</form>
{% endblock %}

templates/vms/installable.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}{% trans "Installable tasks" %}{% endblock %}
{% block content %}
    <h1>Available tasks</h1>
    <hr>

    <table>
    {% for problem in problems %}
        <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title">{% trans 'Problem:' %} <strong>{{ problem }}</strong></h3>
          </div>
          <div class="panel-body">
              <form action="{% url 'vmmanage_install_problem' %}" method="POST">
                  {% csrf_token %}
                  <input type="hidden" name="problem" value="{{ problem }}">
                {{ vagrant_form.as_p }} <input type="submit" value="{% trans 'install' %}" class="btn btn-primary">
              </form>
          </div>
        </div>
    {% endfor %}
    </table>
{% endblock %}

templates/vms/overview.html
{% extends "base.html" %}
{% load i18n %}
{% load vm_extra %}
{% block title %}{% trans "Installed problems" %}{% endblock %}
{% block content %}
    <h1>Installed Problems</h1>
    <hr>

    <table class="table">
            <thead>
              <tr>
                <th>{% trans 'Slug' %}</th>
                <th>{% trans 'Name' %}</th>
                <th>{% trans 'Type' %}</th>
                <th>{% trans 'State' %}</th>
                <th>{% trans 'Last Task' %}</th>
              </tr>
            </thead>
            <tbody>
            {% for problem in problems %}
                      <tr>
                        <td><a href="{% url "vmmanage_detail_problem" problem.slug %}">{{ problem.slug }}</a></td>
                        <td>{{ problem.name }}</td>
                          {% if problem.vm %}
                            <td>{{ problem.vm.provider.capitalize }} {% trans "VM" %}</td>
                            <td class="{{ problem.vm.state_set.latest.name|state_css_class }}">
                                {{ problem.vm.state_set.latest }}
                            </td>
                            <td class="{{ problem.vm.task_set.latest.task.status|task_css_class }}">
                                {{ problem.vm.task_set.latest }}
                            </td>
                          {% else %}
                              <td>{% trans "Download" %}</td>
                              <td></td>
                              <td></td>
                          {% endif %}
                      </tr>
            {% endfor %}
    </table>

{% endblock %}